name: Run notebooks and commit back data/charts

on:
  push:
    branches:
      - master

jobs:
  execute_notebooks:
    runs-on: ubuntu-latest
    container: 
        image: alext234/datascience:latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

            
      - name: Download model
        run: |
           gdown https://drive.google.com/uc?id=1xrxK9swFVlFI-WAYcccIgm0tt9RgawXD
        

            
